### PR TITLE
PortalNetwork: Deal with rough edges in network startup and CLI Support for Portal Network Node

### LINKED ISSUE #700: Deal with rough edges in network startup
The `portalnetwork` class has a few rough edges related to network start up that we should address. These are currently handled by the `cli` package but it can lead to not obvious problems trying to start a client inline.

- The `bindAddress` parameter needs to have a sensible default. If this is undefined, `discv5` crashes the entire application with an uncatchable exception and I'm not sure why
- We should probably embed the bootnode list in the client as an optional default if people want to quick start a node. This will be especially important in the `UltralightProvider` class once we merge that updated code in

### PR DESCRIPTION
**Pull request by cjustinobi**
This PR deals with rough edges in network startup and also implementation for creating and interacting with a Portal Network node. The key features of this PR include:

### UltralightProvider Default
  - Added default `bindaddress` and `bootnodes`

### Portal Network node

- **Dynamic Method Execution**: Adds support for invoking Portal Network methods dynamically based on user input via CLI arguments.
- **CLI Parameters**:
  - `--method`: Specifies the Portal Network method to invoke (e.g., `portal_statePing`).
  - `--params`: Provides JSON-encoded parameters for the method being called.
  - `--port`: Defines the port on which the node will run (default: `9090`).
- **Node Creation**: Implements a `createNode` function to initialize a Portal Network node using `PortalNetwork.create` with secure key generation and multiaddr configuration.
- **Network Messaging**: Adds a helper function, `sendN

### Related Issues
Closes #700

### CODE REVIEW

File: packages/portalnetwork/src/client/provider.ts [hunk 1]
```diff
@@ -34,7 +35,19 @@ export class UltralightProvider {
   }
 
   static async create(opts: Partial<PortalNetworkOpts>): Promise<UltralightProvider> {
-    const portal = await PortalNetwork.create(opts)
+    const finalOpts = {
+      ...DEFAULT_OPTS,
+      ...opts,
+    }
+    
+    if (!finalOpts.bindAddress) {
```
Comment (acolytec3) [inline packages/portalnetwork/src/client/provider.ts:43]: Is this check really needed since you're providing a default value in `DEFAULT_OPTS`?

File: packages/portalnetwork/src/client/provider.ts [hunk 2]
```diff
@@ -34,7 +35,19 @@ export class UltralightProvider {
...
+      throw this.prototype.createError(
+        ERROR_CODES.INVALID_PARAMS,
+        'bindAddress is required for portal network initialization'
+      )
+    }
+
+    const portal = await PortalNetwork.create(finalOpts)
```
Comment (acolytec3) [inline packages/portalnetwork/src/client/provider.ts:50]: @ScottyPoi what do you think about adding these defaults to `PortalNetwork.create` as well?  I'm trying to think of a reason we wouldn't want the bootnodes list to be an optional default in the `create` method for the base client and not just the provider here.

File: packages/portalnetwork/EXAMPLES.md [hunk 3]
```diff
@@ -0,0 +1,50 @@
+# Starting a Portal Network Client
```
Comment (acolytec3) [inline packages/portalnetwork/EXAMPLES.md:1]: This is a really interesting idea but we need to have the example script in `portalnetwork` for this to make sense.  

So, for starters, let's move your `portalClient.ts` script from `packages/cli/scripts` to a new `packages/portalnetwork/examples` directory.

Second, since your code is instantiating an `UltralightProvider` instead of a pure portal network client, can you invoke the `provider.request` method instead of accessing the `provider.portal` APIs?  

Otherwise, can you rewrite the script so it instantiates a pure Portal Network client via `PortalNetwork.create` instead of the provider?

File: packages/cli/scripts/portalClient.ts [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+
+    throw new Error(`Invalid method prefix: ${prefix}. Must be 'portal'`)
+  } catch (error) {
+    console.error('Error executing method:', error)
+    throw error
+  }
+}
+
+async function main() {
+  let node: UltralightProvider | undefined
```
Comment (acolytec3) [inline packages/cli/scripts/portalClient.ts:135]: Let's replace this with a pure `PortalNetwork` client instead of the `UltralightProvider` since you're not accessing the provider methods.

**Review by acolytec3 — CHANGES_REQUESTED** [review]
This is a great start!  Have left some feedback and looking forward to thinking through some of the details.

File: packages/portalnetwork/src/client/provider.ts (hunk 2 above)
Comment (ScottyPoi) [reply packages/portalnetwork/src/client/provider.ts:43]: I think `PortalNetwork.create` should still default to an empty bootnodes list so the client doesn't automatically ping all of the bootnodes every time we run a test

File: packages/portalnetwork/src/util/bootnodes.ts
Comment (ScottyPoi) [inline packages/portalnetwork/src/util/bootnodes.ts:1]: Here is the complete list of the 15 public ultralight nodes:
```ts
const ultralightBootnodes = [
  'enr:-I24QO4X4ECNw19M51l3UYjQPq91dwy7FzEdOb43xEjvGnJMOU2cqD-KQ0FNZbpuzRWyQRiqLinAWw2qsgnRQ2guLt0EY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQOdan7kE4_KU8yM1SNzw9OIrd-oQOlDBnz01fA2fz_1yoN1ZHCCE44',
  'enr:-I24QFm1w_fuMnMf4DsUr_PDVzn_Kn_PY6zQYsoWkJIk4evHUxO8OBacbdo4-7bAyvrXsYgCmOVgOQulvA_9ompMfc8EY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQPeFHF3dY24vc0QgrRIM1vz3ZFnbmddmKLjhP34pxaD5YN1ZHCCE40',
  'enr:-I24QEkyh8nyn2PLMokMXzc_zpuiYxN2VHKrGfU7YI60K9_5YoGZsq-kSngZqLHeOWP3La-Pt5zaojutlsbbsbZ30dYEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQM-ccaM0TOFvYqC_RY_KhZNhEmWx8zdf6AQALhKyMVyboN1ZHCCE4w',
  'enr:-I24QDoMcfNTC3xoH_TSmALXS4WMybTM5SQrysabBxR1DG_UaXHVRHtpQdiGNhxqjHvfSONhnPETB8HorZYplIluDS0EY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQOImp2idIf2UoY-GoY49pOeJAtqeeDLfb5VDxj94h_I44N1ZHCCE48',
  'enr:-I24QHZRM9Sd3UgUOdB443q3nX6NOUsg0VMyarcfD69z8M3SB1vW2hkqiPFczPpyY6wSUCcUeXTig75sC5fT4YnsL7MEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQMGuOLosx85PYtBn7rULoHY9EAtLmGTn7XWoIvFqvq4qIN1ZHCCE5A',
  'enr:-I24QGMQnf1FhP_-tjr7AdT3aJbowJeowuAktBOmoTaxu3WsNPlB1MaD704orcQO8kncLKhEQPOCTv1LSkU27AUldyoEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9-KJc2VjcDI1NmsxoQLJhXByb3LmxHQaqgLDtIGUmpANXaBbFw3ybZWzGqb9-IN1ZHCCE4k',
  'enr:-I24QNw9C_xJvljho0dO27ug7-wZg7KCN1Mmqefdvqwxxqw3X-SLzBO3-KvzCbGFFJJMDn1be6Hd-Bf_TR3afjrwZ7UEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9-KJc2VjcDI1NmsxoQJMpHmGj1xSP1O-Mffk_jYIHVcg6tY5_CjmWVg1gJEsPIN1ZHCCE4o',
  'enr:-I24QOz_tsZ8kOSU_zxXh2HOAxLyAIOeqHZP3Olzgsu73uMRTh8ul7sigT4Q1LaiT12Me2BFm5a4Izi6PCR0_Xe9AHUEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQIdyr0pquxuEW1mHQC0_j0mjB1fIfWZEZLlr7nfaKQXLYN1ZHCCE5E',
  'enr:-I24QD_1X6GriBdbJzOb5bgKqwrZyKHmemXo6OD5h6rmajHhcx0nTEMhqza6BaCA5DNXOi58wszHenV2pIXSTkvGaEsEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQNliw-242ySvi8lxyNOfrkfkC071-aS8iMAYd82EZ1SLYN1ZHCCE5I',
  'enr:-I24QMeElaS4lKvAtYQYmqBkvUc516OLykrLq0DNrw2kuB00EZVXAgFNGlvNz2U1gqVIMzgNg73RPK2j7UT6388HbdcEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9-KJc2VjcDI1NmsxoQKb1jKQ-3sdzLAIL-a-KM4zTVnmgGIKLuKlh61UGoU8jYN1ZHCCE40',
  'enr:-I24QKRKw-asojN9E1YCyJnsyzERVqhnwWFXBobI7E91-LAqFx9IqouzXszzuuh_Q0WzbqFkR32pgCSmPezXcAPeFI0EY4d1IDAuMC4xgmlkgnY0gmlwhKRc9-KJc2VjcDI1NmsxoQMzvDQGNzKQSw3uGSZE86LqS5Xm5KYByI56NOZzTwWiRoN1ZHCCE4w',
  'enr:-I24QK_aSBXvKCAdMsrRioJDSPlJEl79fO5VX2JTrZEks2gbcrarbdfkWMMyEoS_2879w9bnJ14iC9hA6UWexjQ25IYEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQJxPJGDYLZ_QTU310eORFp6-NEs6ThGXpNULnAXPyiKy4N1ZHCCE4o',
  'enr:-I24QDT851x-fW12txAIkCOhq5guf9iMkY7qasRkxfECFsVGS9GnGf_xhy40rAB2aFV8M1kbAo0UMGs-vlDx1JJ1lxQEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9-KJc2VjcDI1NmsxoQKJUamKYO0FWvhv_-H4p1nLdyAqXZWGEzkb9Lk7NtvrR4N1ZHCCE4s',
  'enr:-I24QKa9-vJDAoEiZ4Eio0_z1_fH5OoCAY0mqIuBJ9iJOt9QXie9sAZbrrouToPwTu9hK1CukT7H-qBfdlzMVG2ryy8EY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQKHPt5CQ0D66ueTtSUqwGjfhscU_LiwS28QvJ0GgJFd-YN1ZHCCE4k',
  'enr:-I24QDs2O04xIlgNMLYzChw-YEcsOsVvkuAYVosX4CoDrFGlMbJQHfrodqYH7TvjZ8v1sNUaiG_7mD8LqFsMGhYf80UEY4d1IDAuMC4xgmlkgnY0gmlwhKRc9_OJc2VjcDI1NmsxoQO7DZE841adtMdh8qsDYCDyTjGLud1HZJg-P-OAbTDVz4N1ZHCCE4s',
]
```

**Review by ScottyPoi — DISMISSED** [review]
Thanks this looks great.  There are some of our public bootnodes missing from the list.  We have 15 total.  I left a complete list in a comment.

File: packages/portalnetwork/test/examples/portalClient.spec.ts [hunk 5]
```diff
@@ -0,0 +1,164 @@
+import { PortalNetwork } from '../../../portalnetwork/src'
```
Comment (acolytec3) [inline packages/portalnetwork/test/examples/portalClient.spec.ts:1]: I'm not 100% clear what this is but I think my original request wasn't clear.  We don't need a new test with lots of mocks.  What I was hoping you would do is move the `packages/cli/scripts/portalClient.ts` script to `packages/portalnetwork/examples/portalClient.ts`.  The original script you wrote is actually pretty cool as is for a proof of concept.  

This test script as written isn't really ideal.  I don't think we need a new test specificaly for the default settings and would be okay merging them in without additional tests.

Comment (cjustinobi) [reply packages/portalnetwork/test/examples/portalClient.spec.ts:1]: Updated

File: packages/portalnetwork/examples/portalClient.ts [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+      networkId
+    )
+    return response
+  } catch (error) {
+    console.error('Failed to send network message:', error)
+    throw error
+  }
+}
+
+export async function executeMethod(node: PortalNetwork, method: string, params: any[]) {
```
[the remark this answers is not in the document]
Comment (cjustinobi) [reply packages/portalnetwork/examples/portalClient.ts:102]: Oh, thanks for the heads up

**Review by acolytec3 — APPROVED** [review]
LGTM!
